server.port=8081
spring.application.name=SpringMVC3
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.retries=3
spring.kafka.retry.topic.delay=1000
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.acks=all
logging.level.org.apache.kafka=INFO

app.kafka.orders.topic=new_orders
